version: '3.8'

volumes:
  postgres_data:

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    environment:
      - SECRET_KEY=secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CACHE_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=
      - AZURE_CLIENT_KEY=
      - FILE_STORAGE_HOPE=hope_dedup_engine.apps.core.storage.HOPEAzureStorage?location=hope/
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_period: 5s
      start_interval: 1s
      interval: 5s
      timeout: 4s
      retries: 5

  redis:
    image: redis:7.2
#    ports:
#      - 6379:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      start_interval: 1s
      interval: 5s
      timeout: 4s
      retries: 5

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"
