# ref: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Calculate Release Hash'
description: 'Calculate deps and os hash'
inputs:
  files:
    description: 'Files to use to calculate the hash'
    required: true
    default: "pdm.lock docker/bin/* docker/conf/* docker/Dockerfile"
outputs:
  hash: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.calc.outputs.hash }}

runs:
  using: 'composite'
  steps:
    - id: checksum
      uses: ./.github/actions/checksum
    - id: commit
      uses: ./.github/actions/last_commit
    - id: calc
      shell: bash
      run: |
        build_date=$(date +"%Y-%m-%d %H:%M")
        #        AA='{"CHECKSUM":"${{ steps.checksum.outputs.checksum }}","BUILD_DATE":"${{ steps.checksum.outputs.checksum }}" }'        
        #        
        #        echo "args=${AA}" >> $GITHUB_OUTPUT
        branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        ver="${branch/\//-}"

        echo "CHECKSUM=${{ steps.checksum.outputs.checksum }}" >> $GITHUB_OUTPUT
        echo "BUILD_DATE=${build_date}" >> $GITHUB_OUTPUT
        echo "SOURCE_COMMIT=${{ steps.commit.outputs.last_commit_sha }}" >> $GITHUB_OUTPUT
        echo "VERSION=${ver}" >> $GITHUB_OUTPUT
        echo "GITHUB_SERVER_URL=${{ github.server_url }}" >> $GITHUB_OUTPUT
        echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_OUTPUT
